[package]
name = "webvit"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = { version = "0.3.2", features = ["cuda"] }
candle-nn = { version = "0.3.2", features = ["cuda"] }
candle-optimisers = { version = "0.3.1", features = ["cuda"] }
